/*
 * This class generated by com.mchange.v2.codegen.intfc.DelegatorGenerator
 * Mon Jan 13 15:11:16 IST 2025
 * DO NOT HAND EDIT!!!!
 */
package com.mchange.v2.sql.filter;

import java.io.PrintWriter;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.sql.Connection;
import java.sql.ConnectionBuilder;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.ShardingKeyBuilder;
import java.util.logging.Logger;
import javax.sql.DataSource;

public abstract class FilterDataSource implements DataSource
{
	protected DataSource inner;
	
	public FilterDataSource(DataSource inner)
	{ this.inner = inner; }
	
	public FilterDataSource()
	{}
	
	public void setInner( DataSource inner )
	{ this.inner = inner; }
	
	public DataSource getInner()
	{ return inner; }
	
	public PrintWriter getLogWriter() throws SQLException
	{
		return inner.getLogWriter();
	}
	
	public Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	public Connection getConnection(String a, String b) throws SQLException
	{
		return inner.getConnection(a, b);
	}
	
	public ConnectionBuilder createConnectionBuilder() throws SQLException
	{
		return inner.createConnectionBuilder();
	}
	
	public void setLogWriter(PrintWriter a) throws SQLException
	{
		inner.setLogWriter(a);
	}
	
	public void setLoginTimeout(int a) throws SQLException
	{
		inner.setLoginTimeout(a);
	}
	
	public int getLoginTimeout() throws SQLException
	{
		return inner.getLoginTimeout();
	}
	
	public ShardingKeyBuilder createShardingKeyBuilder() throws SQLException
	{
		return inner.createShardingKeyBuilder();
	}
	
	public Logger getParentLogger() throws SQLFeatureNotSupportedException
	{
		return inner.getParentLogger();
	}
	
	public Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
	public boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
}
