/*
 * This class generated by com.mchange.v2.codegen.intfc.DelegatorGenerator
 * Mon Jan 13 15:11:16 IST 2025
 * DO NOT HAND EDIT!!!!
 */
package com.mchange.v2.sql.filter;

import java.io.PrintWriter;
import java.lang.Class;
import java.lang.Object;
import java.lang.String;
import java.sql.Connection;
import java.sql.ConnectionBuilder;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.ShardingKeyBuilder;
import java.util.logging.Logger;
import javax.sql.DataSource;

public abstract class SynchronizedFilterDataSource implements DataSource
{
	protected DataSource inner;
	
	public SynchronizedFilterDataSource(DataSource inner)
	{ this.inner = inner; }
	
	public SynchronizedFilterDataSource()
	{}
	
	public synchronized void setInner( DataSource inner )
	{ this.inner = inner; }
	
	public synchronized DataSource getInner()
	{ return inner; }
	
	public synchronized PrintWriter getLogWriter() throws SQLException
	{
		return inner.getLogWriter();
	}
	
	public synchronized Connection getConnection() throws SQLException
	{
		return inner.getConnection();
	}
	
	public synchronized Connection getConnection(String a, String b) throws SQLException
	{
		return inner.getConnection(a, b);
	}
	
	public synchronized ConnectionBuilder createConnectionBuilder() throws SQLException
	{
		return inner.createConnectionBuilder();
	}
	
	public synchronized void setLogWriter(PrintWriter a) throws SQLException
	{
		inner.setLogWriter(a);
	}
	
	public synchronized void setLoginTimeout(int a) throws SQLException
	{
		inner.setLoginTimeout(a);
	}
	
	public synchronized int getLoginTimeout() throws SQLException
	{
		return inner.getLoginTimeout();
	}
	
	public synchronized ShardingKeyBuilder createShardingKeyBuilder() throws SQLException
	{
		return inner.createShardingKeyBuilder();
	}
	
	public synchronized Logger getParentLogger() throws SQLFeatureNotSupportedException
	{
		return inner.getParentLogger();
	}
	
	public synchronized Object unwrap(Class a) throws SQLException
	{
		return inner.unwrap(a);
	}
	
	public synchronized boolean isWrapperFor(Class a) throws SQLException
	{
		return inner.isWrapperFor(a);
	}
	
}
